# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_spectra": "01_data.loading.ipynb",
         "get_wetchem": "01_data.loading.ipynb",
         "log_transform_y": "02_data.transform.ipynb",
         "CO2_REGION": "02_data.transform.ipynb",
         "TakeDerivative": "02_data.transform.ipynb",
         "SNV": "02_data.transform.ipynb",
         "DropSpectralRegion": "02_data.transform.ipynb",
         "PRIMARY_COLOR": "03_vis.core.ipynb",
         "ACCENT_COLOR": "03_vis.core.ipynb",
         "DEFAULT_STYLE": "03_vis.core.ipynb",
         "centimeter": "03_vis.core.ipynb",
         "set_style": "03_vis.core.ipynb",
         "plot_spectra": "03_vis.core.ipynb",
         "plot_validation_curve": "03_vis.core.ipynb",
         "plot_learning_curve": "03_vis.core.ipynb",
         "plot_capacity": "03_vis.core.ipynb"}

modules = ["data/loading.py",
           "data/transform.py",
           "vis/core.py"]

doc_url = "https://franckalbinet.github.io/"

git_url = "https://github.com/franckalbinet/mirzoo/"

def custom_doc_links(name): return None
