# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data.loading.ipynb.

# %% auto 0
__all__ = ['get_spectra', 'get_wetchem']

# %% ../nbs/01_data.loading.ipynb 3
from pathlib import Path
import pandas as pd
import pickle
import numpy as np
from fastcore.test import *
from typing import List

pd.set_option('display.max_rows', 500)

# %% ../nbs/01_data.loading.ipynb 4
def get_spectra(fname:str, # folder path containing data
                 org_name:str='organization', # column name containing name of the organization
                 id_name:str='sample_id',# column name containing name of the organization
                 wn_colrange:List[int]=range(2,1703), # column indices of wavenumbers
                ):
    "Loads spectra (features) & associated wavenumbers, organization name, sample ids"
    df = pd.read_csv(fname)                 
    orgs, smp_ids, wns, spectra = [d.to_numpy() for d in [df[org_name], 
                                                          df[id_name], 
                                                          df.columns[wn_colrange].astype(int), 
                                                          df.iloc[:, range(2,1703)]]]
    return orgs, smp_ids, wns, spectra, df

# %% ../nbs/01_data.loading.ipynb 8
def get_wetchem(fname:str, # folder path containing data
                analyte:str='clay_perc', # analyte name
                dropna:bool=True # whether or not you want to get rid of NaN values
                ):
    "Loads wet chemistry (target)"
    df = pd.read_csv(fname)
    df.fillna(df.iloc[:, 2:].mean(), inplace=True)
    df_select = df[analyte]
    y, y_napt = df_select[:60], df_select[60:]
    return y.to_numpy(), y_napt.to_numpy(), df
